---

- name: Install CIFS package
  become: true
  package:
    state: latest
    name:
      - cifs-utils

- name: Creates Multimedia directory
  become: true
  file:
    path: "{{ multimedia_mount_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Store credentials file for the Multimedia volume
  become: true
  when: "cifs_multimedia_password != None and cifs_multimedia_password|length > 0"
  template:
    src: templates/cifs-credentials.ini.j2
    dest: "{{ multimedia_credentials_path }}"
    owner: root
    group: root
    mode: '0400'
  vars:
    username: "{{ ansible_user_id }}"
    password: "{{ cifs_multimedia_password }}"

- name: Check if the credentials file exists
  become: true
  stat: "path={{ multimedia_credentials_path }}"
  register: creds

- name: Fail if the credentials file does not exist
  fail: msg="The credentials file does not exist"
  when: not creds.stat.exists

- name: Mount Multimedia volume
  become: true
  ansible.posix.mount:
    fstype: cifs
    src: "{{ multimedia_cifs_uri }}"
    path: "{{ multimedia_mount_path }}"
    opts: "cred={{ multimedia_credentials_path }},vers=3.0,iocharset=utf8,file_mode=0644,dir_mode=0755,uid={{ ansible_user_uid }},gid={{ ansible_user_gid }}"
    state: mounted
