---

- name: Clone homelab repo
  become: true
  git:
    repo: "{{ homelab_repo_git }}"
    dest: "{{ homelab_repo_dir }}"
    version: main

- name: Symlink the home-assistant configuration
  become: true
  file:
    src: "{{ homelab_repo_dir }}/home-assistant"
    dest: "{{ k8s_volumes_dir }}/home-assistant"
    owner: root
    group: root
    state: link

- name: Creates mosquitto volume
  become: true
  file:
    path: "{{ k8s_volumes_dir }}/mosquitto"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Symlink the mosquitto configuration
  become: true
  file:
    src: "{{ homelab_repo_dir }}/mosquitto"
    dest: "{{ k8s_volumes_dir }}/mosquitto/config"
    owner: root
    group: root
    state: link

- name: Symlink the node-red configuration
  become: true
  file:
    src: "{{ homelab_repo_dir }}/node-red"
    dest: "{{ k8s_volumes_dir }}/node-red"
    owner: root
    group: root
    state: link
