---

- name: Store kubeconfig in variable
  register: microk8s_config
  changed_when: false
  check_mode: false
  command: microk8s config

- name: Check if the local kubeconfig file already exists
  delegate_to: localhost
  register: local_kubeconfig
  stat: 
    path: ~/.kube/config

- name: Create .kube directory
  delegate_to: localhost
  when: local_kubeconfig.stat.exists == false
  file:
    path: ~/.kube
    state: directory
    mode: '0700'

- name: Create .kube/config file
  delegate_to: localhost
  when: local_kubeconfig.stat.exists == false
  copy:
    content: "{{ microk8s_config.stdout }}"
    dest: ~/.kube/config
