---

- name: Checking Operative System (only Debian compatible)
  meta: end_play
  when: ansible_os_family != 'Debian'

- import_tasks: master.yml
- import_tasks: addons.yml
- import_tasks: local-config.yml
- import_tasks: traefik.yml
- import_tasks: home-assistant.yml
