---

- name: Add traefik helm repo
  kubernetes.core.helm_repository:
    name: traefik
    repo_url: https://traefik.github.io/charts

- name: Flush handlers
  meta: flush_handlers

- name: Install traefik
  kubernetes.core.helm:
    name: traefik
    namespace: traefik
    chart_ref: traefik/traefik
    chart_version: "{{ traefik_version }}"
    create_namespace: true
    values:
      ports:
        traefik:
          expose: false
          port: 9000
        web:
          expose: true
          port: 8000
          exposedPort: 80
          nodePort: 80
          redirectTo:
              port: websecure
        websecure:
          expose: true
          port: 8443
          exposedPort: 443
          nodePort: 443
      service:
          enabled: true
          type: NodePort
      ssl:
          enabled: true
          permanentRedirect: false
