---

apiVersion: v1
kind: Secret
metadata:
  name: smb-jdownloader-downloads-credentials
  namespace: jdownloader
  labels:
    app.kubernetes.io/name: jdownloader
type: Opaque
stringData:
  username: ${SMB_NAS_USERNAME}
  password: ${SMB_NAS_PASSWORD}

