---

apiVersion: v1
kind: Service
metadata:
  name: transmission
  namespace: transmission
  labels:
    app.kubernetes.io/name: transmission
spec:
  selector:
    app.kubernetes.io/name: transmission
  ports:
    - name: admin
      protocol: TCP
      port: 9091
      targetPort: admin
