authentik:
  secret_key: ${AUTHENTIK_SECRET_KEY}
  error_reporting:
    enabled: false
  postgresql:
    password: ${AUTHENTIK_PASSWORD}

server:
  ingress:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/hostname: auth.${COMMON_DOMAIN_ROOT}
      external-dns.alpha.kubernetes.io/target: ${COMMON_DNS_IP}
      external-dns.alpha.kubernetes.io/ttl: 1m
    hosts:
      - auth.${COMMON_DOMAIN_ROOT}

postgresql:
  enabled: true
  auth:
    password: ${AUTHENTIK_PASSWORD}
  primary:
    persistence:
      existingClaim: postgresql-data
    containerSecurityContext:
      runAsUser: 1000

redis:
  enabled: true
  master:
    persistence:
      existingClaim: redis-data
    containerSecurityContext:
      runAsUser: 1000

additionalObjects:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: postgresql-data
      labels:
        app.kubernetes.io/name: postgresql
    spec:
      persistentVolumeReclaimPolicy: Retain
      storageClassName: hostpath
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 10Gi
      hostPath:
        path: "${COMMON_VOLUMES_PATH}/authentik/postgresql-data"
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: postgresql-data
      labels:
        app.kubernetes.io/name: postgresql
    spec:
      storageClassName: hostpath
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: redis-data
      labels:
        app.kubernetes.io/name: redis
    spec:
      persistentVolumeReclaimPolicy: Retain
      storageClassName: hostpath
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 10Gi
      hostPath:
        path: "${COMMON_VOLUMES_PATH}/authentik/redis-data"
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: redis-data
      labels:
        app.kubernetes.io/name: redis
    spec:
      storageClassName: hostpath
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
