apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "transmission.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transmission.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: TZ
              value: {{ .Values.transmission.tz }}
            - name: OPENVPN_PROVIDER
              value: {{ .Values.openvpn.provider | quote }}
            - name: OPENVPN_CONFIG
              value: {{ .Values.openvpn.region | quote }}
            - name: OPENVPN_USERNAME
              value: {{ .Values.openvpn.username | quote }}
            - name: OPENVPN_PASSWORD
              value: {{ .Values.openvpn.password | quote }}
            - name: LOCAL_NETWORK
              value: {{ .Values.openvpn.network | quote }}
            - name: OPENVPN_OPTS
              value: {{ .Values.transmission.opts | quote }}
            - name: TRANSMISSION_WEB_UI
              value: {{ .Values.transmission.webUI | quote }}
            - name: TRANSMISSION_DOWNLOAD_QUEUE_SIZE
              value: {{ .Values.transmission.downloadQueueSize | quote }}
            - name: TRANSMISSION_RATIO_LIMIT_ENABLED
              value: {{ .Values.transmission.ratioLimitEnabled | quote }}
            - name: TRANSMISSION_RATIO_LIMIT
              value: {{ .Values.transmission.ratioLimit | quote }}
            - name: TRANSMISSION_SPEED_LIMIT_DOWN
              value: {{ .Values.transmission.speedLimitDown | quote }}
            - name: TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED
              value: {{ .Values.transmission.speedLimitDownEnabled | quote }}
            - name: TRANSMISSION_SPEED_LIMIT_UP
              value: {{ .Values.transmission.speedLimitUp | quote }}
            - name: TRANSMISSION_SPEED_LIMIT_UP_ENABLED
              value: {{ .Values.transmission.speedLimitUpEnabled | quote }}
            - name: WEBPROXY_ENABLED
              value: {{ .Values.transmission.webProxyEnabled | quote }}
          ports:
            - name: admin
              protocol: TCP
              containerPort: {{ .Values.service.port }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
            httpGet:
              path: /
              port: admin
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
            httpGet:
              path: /
              port: admin
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
