apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission.fullname" . }}
  labels:
    {{- include "transmission.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "transmission.selectorLabels" . | nindent 4 }}
  ports:
    - name: admin
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: admin
