---

apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      protocol: TCP
      targetPort: web
      port: 80
      nodePort: 80
    - name: websecure
      protocol: TCP
      targetPort: websecure
      port: 443
      nodePort: 443

