ingressClass:
  enabled: true
  isDefaultClass: true

deployment:
  hostUsers: false

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

ingressRoute:
  dashboard:
    enabled: false

experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: github.com/sevensolutions/traefik-oidc-auth
      version: v0.18.0

ports:
  traefik:
    http: &httpSecurity
      aliasHeadersStrategy: delete
      encodedCharacters:
        allowEncodedSlash: false
        allowEncodedBackSlash: false
        allowEncodedNullCharacter: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: false
        allowEncodedHash: false
  metrics:
    http: *httpSecurity
  web:
    hostPort: 80
    http:
      <<: *httpSecurity
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    hostPort: 443
    http: *httpSecurity
  mqtt:
    port: 1883
    expose:
      default: true
    exposedPort: 1883
    protocol: TCP
    hostPort: 1883
    http: *httpSecurity

service:
  spec:
    type: ClusterIP
  annotations:
    external-dns.alpha.kubernetes.io/hostname: k8s.${COMMON_DOMAIN_ROOT}
    external-dns.alpha.kubernetes.io/target: ${COMMON_DNS_IP}
    external-dns.alpha.kubernetes.io/ttl: 1m

providers:
  kubernetesCRD:
    allowCrossNamespace: false
    safeNaming: true

extraObjects:
  - |
    apiVersion: traefik.io/v1alpha1
    kind: TLSStore
    metadata:
      name: default
    spec:
      defaultCertificate:
        secretName: ${CERTMANAGER_CERT_SECRET_NAME}
  - |
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: ${CERTMANAGER_CERT_NAME}
    spec:
      secretName: ${CERTMANAGER_CERT_SECRET_NAME}
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      dnsNames:
        - "*.${COMMON_DOMAIN_ROOT}"
  - |
    apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: oidc-pocketid
      namespace: traefik
    spec:
        plugin:
          traefik-oidc-auth:
            Secret: ${POCKETID_SECRET}
            Scopes: ["openid", "profile", "email"]
            Provider:
              Url: https://auth.${COMMON_DOMAIN_ROOT}
              ClientId: ${POCKETID_CLIENT_ID}
              ClientSecret: ${POCKETID_CLIENT_SECRET}
