---

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-smb-node
  namespace: kube-system
  labels:
    app.kubernetes.io/name: csi-driver-smb
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: csi-driver-smb
      app: csi-smb-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: csi-driver-smb
        app: csi-smb-node
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: csi-smb-node-sa
      priorityClassName: system-cluster-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - operator: Exists
      containers:
        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.13.1
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --http-endpoint=localhost:29643
            - --v=2
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.11.1
          args:
            - --csi-address=$$(ADDRESS)
            - --kubelet-registration-path=$$(DRIVER_REG_SOCK_PATH)
            - --v=2
          livenessProbe:
            initialDelaySeconds: 30
            timeoutSeconds: 15
            exec:
              command:
                - /csi-node-driver-registrar
                - --kubelet-registration-path=$$(DRIVER_REG_SOCK_PATH)
                - --mode=kubelet-registration-probe
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/smb.csi.k8s.io/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
        - name: smb
          image: "registry.k8s.io/sig-storage/smbplugin:v1.15.0"
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--drivername=smb.csi.k8s.io"
            - "--endpoint=$$(CSI_ENDPOINT)"
            - "--nodeid=$$(KUBE_NODE_NAME)"
            - "--enable-get-volume-stats=true"
            - "--krb5-prefix="
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
            httpGet:
              host: localhost
              path: /healthz
              port: 29643
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
              name: mountpoint-dir
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/smb.csi.k8s.io
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/
            type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
