---

apiVersion: v1
kind: Secret
metadata:
  name: library-smb
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
type: Opaque
stringData:
  username: ${SMB_NAS_USERNAME}
  password: ${SMB_NAS_PASSWORD}

