---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-plex-multimedia
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0755
    - file_mode=0644
  capacity:
    storage: ${SMB_NAS_SIZE}
  accessModes:
    - ReadWriteMany
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: nas#plex#multimedia
    volumeAttributes:
      source: ${SMB_NAS_SOURCE_MULTIMEDIA}
    nodeStageSecretRef:
      name: smb-plex-multimedia-credentials
      namespace: plex

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smb-plex-multimedia
  namespace: plex
spec:
  volumeName: smb-plex-multimedia
  storageClassName: smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${SMB_NAS_SIZE}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pms-config
  namespace: plex
  labels:
    app.kubernetes.io/name: plex
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "${COMMON_VOLUMES_PATH}/plex"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: plex-pms-config
  namespace: plex
spec:
  volumeName: plex-pms-config
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
