---

apiVersion: v1
kind: Secret
metadata:
  name: smb-transmission-downloads-credentials
  namespace: transmission
  labels:
    app.kubernetes.io/name: transmission
type: Opaque
stringData:
  username: ${SMB_NAS_USERNAME}
  password: ${SMB_NAS_PASSWORD}

