---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-transmission-downloads
  namespace: transmission
  labels:
    app.kubernetes.io/name: transmission
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0755
    - file_mode=0644
  capacity:
    storage: ${SMB_NAS_SIZE}
  accessModes:
    - ReadWriteMany
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: nas#transmission#downloads
    volumeAttributes:
      source: ${SMB_NAS_SOURCE_DOWNLOADS}
    nodeStageSecretRef:
      name: smb-transmission-downloads-credentials
      namespace: transmission

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: smb-transmission-downloads
  namespace: transmission
spec:
  volumeName: smb-transmission-downloads
  storageClassName: smb
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${SMB_NAS_SIZE}
