---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.0.1/charts/other/app-template/values.schema.json

defaultPodOptions:
  terminationGracePeriodSeconds: 30

controllers:
  jdownloader:
    type: deployment
    strategy: RollingUpdate
    annotations:
      keel.sh/policy: major
      keel.sh/trigger: poll
      keel.sh/pollSchedule: "@midnight"
    containers:
      jdownloader:
        image:
          repository: jlesage/jdownloader-2
          tag: "${DOCKER_TAG__JDOWNLOADER__DEPLOYMENT__JDOWNLOADER__0}"
        env:
          TZ: ${COMMON_TZ}
          DARK_MODE: 1
          KEEP_APP_RUNNING: 1
          USER_ID: 1000
          GROUP_ID: 100
        ports:
          - name: http
            protocol: TCP
            containerPort: 5800
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /
                port: http
          readiness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /
                port: http

service:
  jdownloader:
    controller: jdownloader
    ports:
      http:
        port: 5800
        targetPort: http

ingress:
  main:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: jd.${COMMON_DOMAIN_ROOT}
      external-dns.alpha.kubernetes.io/target: ${COMMON_DNS_IP}
      external-dns.alpha.kubernetes.io/ttl: 1m
    hosts:
      - host: "jd.${COMMON_DOMAIN_ROOT}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: jdownloader
              port: http

secrets:
  smb-downloads-credentials:
    suffix: smb-downloads-credentials
    stringData:
      username: ${NAS_SMB_USERNAME}
      password: ${NAS_SMB_PASSWORD}

persistence:
  config:
    type: hostPath
    hostPath: ${COMMON_VOLUMES_PATH}/jdownloader
    hostPathType: DirectoryOrCreate
    advancedMounts:
      jdownloader:
        jdownloader:
          - path: /config

  smb-downloads:
    type: persistentVolumeClaim
    suffix: smb-downloads
    storageClass: smb
    accessMode: ReadWriteMany
    size: ${NAS_SMB_SIZE}
    advancedMounts:
      jdownloader:
        jdownloader:
          - path: /output

rawResources:
  smb-downloads:
    apiVersion: v1
    kind: PersistentVolume
    suffix: smb-downloads
    annotations:
      pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
    spec:
      spec:
        persistentVolumeReclaimPolicy: Retain
        storageClassName: smb
        mountOptions:
          - dir_mode=0755
          - file_mode=0644
          - uid=1000
          - gid=100
        capacity:
          storage: ${NAS_SMB_SIZE}
        accessModes:
          - ReadWriteMany
        csi:
          driver: smb.csi.k8s.io
          volumeHandle: nas#jdownloader#downloads-jdownloader
          volumeAttributes:
            source: ${NAS_SMB_SOURCE_DOWNLOADS}/jdownloader
          nodeStageSecretRef:
            name: '{{- (include "bjw-s.common.lib.chart.names.fullname" $) -}}-smb-downloads-credentials'
            namespace: "{{ .Release.Namespace }}"
