---

apiVersion: v1
kind: Service
metadata:
  name: keel
  namespace: keel
  labels:
    app.kubernetes.io/name: keel
spec:
  selector:
    app.kubernetes.io/name: keel
  ports:
    - name: keel
      protocol: TCP
      port: 9300
      targetPort: keel
