basicauth:
  enabled: false

auth:
  mode: external-proxy
  proxyUserHeader: X-Forwarded-User
  proxyLogoutURL: /oauth2/sign_out?rd=/

oauth2Proxy:
  enabled: true
  existingSecret: keel-oauth2-proxy
  extraArgs:
    - --provider=oidc
    - --oidc-issuer-url=https://auth.${COMMON_DOMAIN_ROOT}
    - --redirect-url=https://keel.${COMMON_DOMAIN_ROOT}/oauth2/callback
    - --email-domain=*
    - --scope=openid profile email
    - --prefer-email-to-user=true
    - --cookie-secure=true
    - --cookie-name=__Host-keel
    - --code-challenge-method=S256
    - --skip-provider-button=true

helmProvider:
  enabled: false

insecureRegistry: true

ingress:
  enabled: true
  annotations:
    external-dns.kubernetes.io/hostname: keel.${COMMON_DOMAIN_ROOT}
    external-dns.kubernetes.io/target: k8s.${COMMON_DOMAIN_ROOT}
    external-dns.kubernetes.io/ttl: 1m
  hosts:
    - host: keel.${COMMON_DOMAIN_ROOT}
      paths:
        - /

podSecurityContext:
  fsGroup: 100
  fsGroupChangePolicy: OnRootMismatch

containerSecurityContext:
  runAsUser: 1000
  runAsGroup: 100
  readOnlyRootFilesystem: true

service:
  enabled: true
  type: ClusterIP

persistence:
  enabled: true
  storageClass: local-path-delete
