nameOverride: plex
fullnameOverride: plex

image:
  tag: "1.40.4.8679-424562606"

ingress:
  enabled: true
  url: https://plex.${COMMON_DOMAIN_ROOT}
  #ingressClassName: "ingress-ngin"

pms:
  configExistingClaim: "pms-config"

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

extraEnv:
  PLEX_CLAIM: ${PLEX_CLAIM}
  TZ: ${COMMON_TZ}
  PLEX_UID: "1000"
  PLEX_GID: "100"


# Optionally specify additional volume mounts for the PMS and init containers.
extraVolumeMounts:
  - name: pms-quicksync
    mountPath: /dev/dri
  - name: pms-library
    mountPath: /media/Multimedia

# Optionally specify additional volumes for the pod.
extraVolumes:
  - name: pms-quicksync
    hostPath:
      path: /dev/dri
      type: Directory
  - name: pms-library
    persistentVolumeClaim:
      claimName: smb-plex-multimedia
