---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

defaultPodOptions:
  terminationGracePeriodSeconds: 30
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "network-vlan-sot", "namespace": "kube-system", "mac":"e6:99:c8:2e:b8:ea" }]'

controllers:
  plex:
    type: statefulset
    containers:
      plex:
        image:
          repository: plexinc/pms-docker
          tag: "${DOCKER_TAG__PLEX__STATEFULSET__PLEX__0}"
        securityContext:
          privileged: true # TODO: needed for quicksync
        env:
          PLEX_CLAIM: ${PLEX_CLAIM}
          TZ: ${COMMON_TZ}
          PLEX_UID: 1000
          PLEX_GID: 100
        ports:
          - name: http
            protocol: TCP
            containerPort: 32400
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /identity
                port: http
          readiness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /identity
                port: http

service:
  plex:
    controller: plex
    ports:
      http:
        port: 32400
        targetPort: http

ingress:
  main:
    hosts:
      - host: "plex.${COMMON_DOMAIN_ROOT}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: plex
              port: http

secrets:
  smb-multimedia-credentials:
    stringData:
      username: ${NAS_SMB_USERNAME}
      password: ${NAS_SMB_PASSWORD}

persistence:
  transcode:
    type: emptyDir
    advancedMounts:
      plex:
        plex:
          - path: /transcode
  quicksync:
    type: hostPath
    hostPath: /dev/dri
    hostPathType: Directory
    advancedMounts:
      plex:
        plex:
          - path: /dev/dri
  config:
    type: hostPath
    hostPath: ${COMMON_VOLUMES_PATH}/plex
    hostPathType: DirectoryOrCreate
    advancedMounts:
      plex:
        plex:
          - path: /config
  smb-multimedia:
    type: persistentVolumeClaim
    storageClass: smb
    accessMode: ReadOnlyMany
    size: ${NAS_SMB_SIZE}
    advancedMounts:
      plex:
        plex:
          - path: /media/Multimedia

rawResources:
  smb-multimedia:
    apiVersion: v1
    kind: PersistentVolume
    annotations:
      pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
    spec:
      spec:
        persistentVolumeReclaimPolicy: Retain
        storageClassName: smb
        mountOptions:
          - dir_mode=0555
          - file_mode=0444
          - uid=0
          - gid=0
        capacity:
          storage: ${NAS_SMB_SIZE}
        accessModes:
          - ReadOnlyMany
        csi:
          driver: smb.csi.k8s.io
          volumeHandle: nas#plex#multimedia
          volumeAttributes:
            source: ${NAS_SMB_SOURCE_MULTIMEDIA}
          nodeStageSecretRef:
            name: "{{- (include \"bjw-s.common.lib.chart.names.fullname\" $) -}}-smb-multimedia-credentials"
            namespace: "{{ .Release.Namespace }}"
