# General Config
homeassistant:
  name: Home
  country: JP
  currency: JPY
  customize: !include others/customize.yaml
  elevation: !secret ha_elevation
  external_url: !secret ha_external_url
  internal_url: !secret ha_internal_url
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  packages: !include_dir_named packages
  temperature_unit: C
  time_zone: Asia/Tokyo
  unit_system: metric
  auth_providers:
    - type: homeassistant

# Frontend
frontend:
  themes: !include_dir_merge_named themes

# Custom Panels
panel_iframe:
  nodered:
    title: Node Red
    url: !secret iframe_nodered_url
    icon: mdi:lan
    require_admin: true
  zigbee2mqtt:
    title: Zigbee
    url: !secret iframe_zigbee2mqtt_url
    icon: mdi:zigbee
    require_admin: true


# Proxy Config
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - !secret ha_proxy_url

# Enable default config + logging
default_config:
logger: !include others/logger.yaml
recorder: !include others/recorder.yaml

# Smart Home Config
automation ui: !include automations.yaml
automation yaml: !include_dir_merge_list automations
group: !include others/groups.yaml
lovelace: !include dashboards/lovelace.yaml
scene: !include scenes.yaml
scene yaml: !include_dir_merge_list scenes
script: !include_dir_merge_named scripts

# Devices
climate: !include devices/climate.yaml
media_player: !include devices/media_players.yaml
input_boolean: !include devices/input_booleans.yaml
spotcast: !include devices/spotcast.yaml
timer: !include devices/timers.yaml
sensor: !include devices/sensors.yaml

# Third party plugins
smartir:
nature_remo:
  access_token: !secret nature_remo_at
