---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

defaultPodOptions:
  terminationGracePeriodSeconds: 30
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/macvlan-iot

controllers:
  home-assistant:
    type: deployment
    annotations:
      keel.sh/policy: major
      keel.sh/trigger: poll
      keel.sh/pollSchedule: "0 0 4 * * 5" # 4am Fri
    containers:
      home-assistant:
        image:
          repository: linuxserver/homeassistant
          tag: "2024.7.4"
        env:
          TZ: ${COMMON_TZ}
          PUID: 1000
          PGID: 100
        ports:
          - name: http
            protocol: TCP
            containerPort: 8123
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /
                port: http
          readiness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /
                port: http

service:
  home-assistant:
    controller: home-assistant
    ports:
      http:
        port: 8123
        targetPort: http

ingress:
  main:
    hosts:
      - host: "ha.${COMMON_DOMAIN_ROOT}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: home-assistant
              port: http

persistence:
  config:
    type: hostPath
    hostPath: ${COMMON_VOLUMES_PATH}/home-assistant
    hostPathType: DirectoryOrCreate
    advancedMounts:
      home-assistant:
        home-assistant:
          - path: /config
