---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.0/charts/other/app-template/values.schema.json

defaultPodOptions:
  terminationGracePeriodSeconds: 30
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "network-vlan-server", "namespace": "kube-system", "mac":"62:e5:28:8e:7a:de" }]'

controllers:
  home-assistant:
    type: deployment
    strategy: Recreate # TODO: How does forcing the MAC affect a RollingUpdate release?
    annotations:
      keel.sh/policy: major
      keel.sh/trigger: poll
      keel.sh/pollSchedule: "0 0 4 * * 5" # 4am Fri
    containers:
      home-assistant:
        image:
          repository: linuxserver/homeassistant
          tag: "${DOCKER_TAG__HOME_ASSISTANT__DEPLOYMENT__HOME_ASSISTANT__0}"
        env:
          TZ: ${COMMON_TZ}
          PUID: 1000
          PGID: 100
          PYTHONPATH: /config/deps/
        ports:
          - name: http
            protocol: TCP
            containerPort: 8123
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /
                port: http
          readiness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /
                port: http
    initContainers:
      git:
        image:
          repository: bitnami/git
          tag: latest
        command: ["/bin/bash"]
        args:
          - -c
          - >-
            git clone ${HOMELAB_REPO} /repo &&
            chown -R 1000:100 /repo &&
            cp -R /repo/${HOMELAB_HA_CONFIG}/{.,}* /config

service:
  home-assistant:
    controller: home-assistant
    ports:
      http:
        port: 8123
        targetPort: http

ingress:
  main:
    hosts:
      - host: "ha.${COMMON_DOMAIN_ROOT}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: home-assistant
              port: http

secrets:
  secrets:
    stringData:
      secrets.yaml: |+
        ha_external_url: ${HA_INTERNAL_URL}
        ha_internal_url: ${HA_EXTERNAL_URL}

        ha_home_latitude: ${HA_HOME_LATITUDE}
        ha_home_longitude: ${HA_HOME_LONGITUDE}
        ha_home_elevation: ${HA_HOME_ELEVATION}

        spotcast_sp_dc: ${HA_SPOTCAST_SP_DC}
        spotcast_sp_key: ${HA_SPOTCAST_SP_KEY}

persistence:
  config:
    type: hostPath
    hostPath: ${COMMON_VOLUMES_PATH}/home-assistant
    hostPathType: DirectoryOrCreate
    advancedMounts:
      home-assistant:
        git:
          - path: /config
        home-assistant:
          - path: /config
  secrets:
    type: secret
    name: "{{- (include \"bjw-s.common.lib.chart.names.fullname\" $) -}}-secrets"
    advancedMounts:
      home-assistant:
        home-assistant:
          - path: /config/secrets.yaml
            subPath: secrets.yaml
