---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-data
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: node-red
spec:
  volumeName: node-red-data
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red-data
  labels:
    app.kubernetes.io/name: node-red
spec:
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  local:
    path: /mnt/host/node-red
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - mimas 
