homeassistant:
  name: Home
  country: SG
  currency: SGD
  customize: !include others/customize.yaml
  external_url: !secret ha_external_url
  internal_url: !secret ha_internal_url
  latitude: !secret ha_home_latitude
  longitude: !secret ha_home_longitude
  elevation: !secret ha_home_elevation
  packages: !include_dir_named packages
  temperature_unit: C
  time_zone: Asia/Singapore
  unit_system: metric
  auth_providers:
    - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 10.0.0.0/8

default_config:
logger: !include others/logger.yaml
recorder: !include others/recorder.yaml

automation ui: !include automations.yaml
automation yaml: !include_dir_merge_list automations
group: !include others/groups.yaml
lovelace: !include dashboards/lovelace.yaml
scene: !include scenes.yaml
scene yaml: !include_dir_merge_list scenes
script: !include_dir_merge_named scripts

media_player: !include devices/media_players.yaml
input_boolean: !include devices/input_booleans.yaml
spotcast: !include devices/spotcast.yaml
timer: !include devices/timers.yaml
sensor: !include devices/sensors.yaml
