---

apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
type: Opaque
stringData:
  api-token: ${CLOUDFLARE_TOKEN}
