apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${CERTMANAGER_CLOUDFLARE_EMAIL}
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          cloudflare:
            email: ${CERTMANAGER_CLOUDFLARE_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
