crds:
  enabled: true

prometheus:
  enabled: false

extraObjects:
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
      labels:
        app.kubernetes.io/name: cert-manager
    type: Opaque
    stringData:
      api-token: ${CERTMANAGER_CLOUDFLARE_TOKEN}
