crds:
  enabled: true

prometheus:
  enabled: false

extraObjects:
  - |
    apiVersion: v1
    kind: Secret
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
      labels:
        app.kubernetes.io/name: cert-manager
    type: Opaque
    stringData:
      api-token: ${CERTMANAGER_CLOUDFLARE_TOKEN}
  - |
    apiVersion: cert-manager.io/v1
    kind: ClusterIssuer
    metadata:
      name: letsencrypt-prod
      namespace: cert-manager
      labels:
        app.kubernetes.io/name: cert-manager
    spec:
      acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ${CERTMANAGER_CLOUDFLARE_EMAIL}
        privateKeySecretRef:
          name: letsencrypt-prod-key
        solvers:
          - dns01:
              cloudflare:
                email: ${CERTMANAGER_CLOUDFLARE_EMAIL}
                apiTokenSecretRef:
                  name: cloudflare-api-token
                  key: api-token
  - |
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: ${CERTMANAGER_CERT_NAME}
      namespace: traefik
    spec:
      secretName: ${CERTMANAGER_CERT_SECRET_NAME}
      issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
      dnsNames:
        - "*.${COMMON_DOMAIN_ROOT}"
