---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.1.2/charts/other/app-template/values.schema.json

defaultPodOptions:
  terminationGracePeriodSeconds: 30

controllers:
  changedetection:
    type: deployment
    replicas: 0 # Disable for now
    annotations:
      keel.sh/policy: major
      keel.sh/trigger: poll
      keel.sh/pollSchedule: "@midnight"
    containers:
      changedetection:
        image:
          repository: linuxserver/changedetection.io
          tag: "${DOCKER_TAG__CHANGEDETECTION__DEPLOYMENT__CHANGEDETECTION__0}"
        env:
          TZ: ${COMMON_TZ}
          PUID: 1000
          PGID: 100
          PLAYWRIGHT_DRIVER_URL: ws://localhost:3000
        ports:
          - name: http
            protocol: TCP
            containerPort: 5000
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /
                port: http
          readiness:
            enabled: true
            custom: true
            spec:
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 2
              successThreshold: 1
              failureThreshold: 5
              httpGet:
                path: /
                port: http
      browserless:
        image:
          repository: browserless/chrome
          tag: latest
        env:
          SCREEN_WIDTH: 800
          SCREEN_HEIGHT: 600
          SCREEN_DEPTH: 16
          ENABLE_DEBUGGER: false
          PREBOOT_CHROME: true
          CONNECTION_TIMEOUT: 300000
          MAX_CONCURRENT_SESSIONS: 2
          CHROME_REFRESH_TIME: 600000
          DEFAULT_BLOCK_ADS: true
          DEFAULT_STEALTH: true
          DEFAULT_IGNORE_HTTPS_ERRORS: true
        ports:
          - name: browserless
            containerPort: 3000

service:
  changedetection:
    controller: changedetection
    ports:
      http:
        port: 5000
        targetPort: http

ingress:
  main:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: cd.${COMMON_DOMAIN_ROOT}
      external-dns.alpha.kubernetes.io/target: ${COMMON_DNS_IP}
      external-dns.alpha.kubernetes.io/ttl: 5m
    hosts:
      - host: "cd.${COMMON_DOMAIN_ROOT}"
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: changedetection
              port: http

persistence:
  config:
    type: hostPath
    hostPath: ${COMMON_VOLUMES_PATH}/changedetection
    hostPathType: DirectoryOrCreate
    advancedMounts:
      changedetection:
        changedetection:
          - path: /config
