guests:
  name: Guests at Home
  icon: mdi:account-plus

holidays:
  name: Holidays Mode
  icon: mdi:beach

home_ac_automations:
  name: Home AC Automations
  initial: 'on'
  icon: mdi:air-conditioner

home_light_automations:
  name: Home Light Automations
  initial: 'on'
  icon: mdi:lightbulb-alert

home_locked:
  name: Home Locked
  icon: mdi:shield-lock

home_vacuumed:
  name: Home vacuumed today
  icon: mdi:robot-vacuum
