guests:
  name: Guests at Home
  initial: 'off'
  icon: mdi:account-plus

holidays:
  name: Holidays Mode
  initial: 'off'
  icon: mdi:beach

home_light_automations:
  name: Home Light Automations
  initial: 'on'
  icon: mdi:lightbulb-alert

home_locked:
  name: Home Locked
  initial: 'off'
  icon: mdi:shield-lock

home_vacuumed:
  name: Home vacuumed today
  initial: 'off'
  icon: mdi:robot-vacuum
