metadata:
  org: github.com/igalarzab/homelab
  maintainer: Jose Galarza

namespaces:
  kube-system:
  cert-manager:
  traefik:
  keel:
  plex:

helmRepos:
  csi-driver-smb: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  jetstack: https://charts.jetstack.io
  keel: https://charts.keel.sh
  plex: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
  traefik: https://traefik.github.io/charts

appsTemplates:
  default: &default
    enabled: true
    protected: false
    test: false
    wait: false

apps:
  csi-driver-smb:
    <<: *default
    chart: csi-driver-smb/csi-driver-smb
    version: v1.15.0
    namespace: kube-system
    priority: -100
  cert-manager:
    <<: *default
    chart: jetstack/cert-manager
    version: v1.15.2
    namespace: cert-manager
    valuesFile: cert-manager.values.yml
    priority: -99
    enabled: false # TODO
  traefik:
    <<: *default
    chart: traefik/traefik
    version: v30.0.2
    namespace: traefik
    valuesFile: traefik.values.yml
    priority: -98
  keel:
    <<: *default
    chart: keel/keel
    version: 1.0.3
    namespace: keel
    valuesFile: keel.values.yml
    priority: -89
  plex:
    <<: *default
    chart: plex/plex-media-server
    version: 0.4.0
    namespace: keel
    valuesFile: plex.values.yml
    priority: -89
    enabled: false # TODO

