metadata:
  org: github.com/igalarzab/homelab
  maintainer: Jose Galarza

namespaces:
  kube-system:
  cert-manager:
  home-assistant:
  jdownloader:
  traefik:
  transmission:
  keel:
  plex:

helmRepos:
  bitnami: https://charts.bitnami.com/bitnami
  bjw-s: https://bjw-s.github.io/helm-charts
  csi-driver-smb: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  jetstack: https://charts.jetstack.io
  keel: https://charts.keel.sh
  traefik: https://traefik.github.io/charts

appsTemplates:
  default: &default
    enabled: true
    protected: false
    test: false
    wait: true

apps:
  csi-driver-smb:
    <<: *default
    chart: csi-driver-smb/csi-driver-smb
    version: v1.15.0
    namespace: kube-system
    priority: -100
  multus-cni:
    <<: *default
    chart: bitnami/multus-cni
    version: 2.1.10
    namespace: kube-system
    valuesFile: multus-cni/values.yml
    priority: -99
  cert-manager:
    <<: *default
    chart: jetstack/cert-manager
    version: v1.15.2
    namespace: cert-manager
    valuesFile: cert-manager/values.yml
    priority: -98
    hooks:
      postInstall: cert-manager/post-install.yml
  traefik:
    <<: *default
    chart: traefik/traefik
    version: v30.0.2
    namespace: traefik
    valuesFile: traefik/values.yml
    priority: -97
  keel:
    <<: *default
    chart: keel/keel
    version: 1.0.3
    namespace: keel
    valuesFile: keel/values.yml
    priority: -89
    enabled: false # TODO: Not using for now
  transmission:
    <<: *default
    chart: ./transmission/chart
    version: 0.1.0
    namespace: transmission
    valuesFile: transmission/values.yml
    priority: -79
  jdownloader:
    <<: *default
    chart: ./jdownloader/chart
    version: 0.1.0
    namespace: jdownloader
    valuesFile: jdownloader/values.yml
    priority: -78
  plex:
    <<: *default
    chart: ./plex/chart
    version: 0.1.0
    namespace: plex
    valuesFile: plex/values.yml
    priority: -69
  mosquitto:
    <<: *default
    chart: bjw-s/app-template
    version: 3.3.2
    namespace: home-assistant
    valuesFile: home-assistant/mosquitto.values.yml
    priority: -59
  zigbee2mqtt:
    <<: *default
    chart: bjw-s/app-template
    version: 3.3.2
    namespace: home-assistant
    valuesFile: home-assistant/zigbee2mqtt.values.yml
    priority: -58
  node-red:
    <<: *default
    chart: bjw-s/app-template
    version: 3.3.2
    namespace: home-assistant
    valuesFile: home-assistant/nodered.values.yml
    priority: -57
  esphome:
    <<: *default
    chart: bjw-s/app-template
    version: 3.3.2
    namespace: home-assistant
    valuesFile: home-assistant/esphome.values.yml
    priority: -56
  home-assistant:
    <<: *default
    chart: bjw-s/app-template
    version: 3.3.2
    namespace: home-assistant
    valuesFile: home-assistant/home-assistant.values.yml
    priority: -55
