metadata:
  org: github.com/igalarzab/homelab
  maintainer: Jose Galarza

settings:
  kubeContext: saturn

namespaces:
  cert-manager:
  cloudflare-ddns:
  external-dns:
  home-assistant:
  jdownloader:
  keel:
  kube-system:
  mosquitto:
  plex:
  pocket-id:
  traefik:

helmRepos:
  bitnami: https://charts.bitnami.com/bitnami
  bjw-s: https://bjw-s-labs.github.io/helm-charts
  containeroo: https://charts.containeroo.ch
  csi-driver-smb: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  external-dns: https://kubernetes-sigs.github.io/external-dns/
  metrics-server: https://kubernetes-sigs.github.io/metrics-server/
  jetstack: https://charts.jetstack.io
  keel: https://charts.keel.sh
  traefik: https://traefik.github.io/charts

appsTemplates:
  default: &default
    enabled: true
    protected: false
    test: false
    wait: true

apps:
  csi-driver-smb:
    <<: *default
    chart: csi-driver-smb/csi-driver-smb
    version: "1.20.3"
    namespace: kube-system
  local-path-provisioner:
    <<: *default
    chart: containeroo/local-path-provisioner
    version: "0.0.38"
    namespace: kube-system
    valuesFile: local-path-provisioner/values.yml
    hooks:
      postInstall: local-path-provisioner/post-install.yml
      postUpgrade: local-path-provisioner/post-install.yml
  csi-driver-proxmox:
    <<: *default
    chart: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    version: "0.5.12"
    namespace: kube-system
    valuesFile: csi-driver-proxmox/values.yml
  multus-cni:
    <<: *default
    chart: bitnami/multus-cni
    version: "2.2.21"
    namespace: kube-system
    valuesFile: multus-cni/values.yml
  metrics-server:
    <<: *default
    chart: metrics-server/metrics-server
    version: "3.14.0"
    namespace: kube-system
    valuesFile: metrics-server/values.yml
  cert-manager:
    <<: *default
    chart: jetstack/cert-manager
    version: "v1.21.1"
    namespace: cert-manager
    valuesFile: cert-manager/values.yml
    hooks:
      postInstall: cert-manager/post-install.yml
      postUpgrade: cert-manager/post-install.yml
  external-dns:
    <<: *default
    chart: external-dns/external-dns
    version: "1.21.1"
    namespace: external-dns
    valuesFile: external-dns/values.yml
  traefik:
    <<: *default
    chart: traefik/traefik
    version: "41.5.0"
    namespace: traefik
    valuesFile: traefik/values.yml
  pocket-id:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: pocket-id
    valuesFile: pocket-id/values.yml
  keel:
    <<: *default
    chart: keel/keel
    version: "1.2.2"
    namespace: keel
    valuesFile: keel/values.yml
  cloudflare-ddns:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: cloudflare-ddns
    valuesFile: cloudflare-ddns/values.yml
  plex:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: plex
    valuesFile: plex/values.yml
  jdownloader:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: jdownloader
    valuesFile: jdownloader/values.yml
  mosquitto:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: mosquitto
    valuesFile: mosquitto/values.yml
  zigbee2mqtt:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: home-assistant
    valuesFile: home-assistant/zigbee2mqtt.values.yml
  node-red:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: home-assistant
    valuesFile: home-assistant/nodered.values.yml
  esphome:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: home-assistant
    valuesFile: home-assistant/esphome.values.yml
  mmwave-configurator:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: home-assistant
    valuesFile: home-assistant/mmwave-configurator.values.yml
  otbr:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: home-assistant
    valuesFile: home-assistant/otbr.values.yml
  matter-server:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: home-assistant
    valuesFile: home-assistant/matter-server.values.yml
  home-assistant:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: home-assistant
    valuesFile: home-assistant/home-assistant.values.yml
