metadata:
  org: github.com/igalarzab/homelab
  maintainer: Jose Galarza

namespaces:
  authentik:
  cert-manager:
  changedetection:
  cloudflare-ddns:
  external-dns:
  home-assistant:
  jdownloader:
  keel:
  kube-system:
  mcps:
  mosquitto:
  plex:
  traefik:

helmRepos:
  authentik: https://charts.goauthentik.io
  bitnami: https://charts.bitnami.com/bitnami
  bjw-s: https://bjw-s-labs.github.io/helm-charts
  csi-driver-smb: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  external-dns: https://kubernetes-sigs.github.io/external-dns/
  metrics-server: https://kubernetes-sigs.github.io/metrics-server/
  jetstack: https://charts.jetstack.io
  keel: https://charts.keel.sh
  traefik: https://traefik.github.io/charts

appsTemplates:
  default: &default
    enabled: true
    protected: false
    test: false
    wait: true

apps:
  csi-driver-smb:
    <<: *default
    chart: csi-driver-smb/csi-driver-smb
    version: "v1.18.0"
    namespace: kube-system
    priority: -109
  csi-driver-proxmox:
    <<: *default
    chart: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    version: "0.3.13"
    namespace: kube-system
    valuesFile: csi-driver-proxmox/values.yml
    priority: -108
  multus-cni:
    <<: *default
    chart: bitnami/multus-cni
    version: "2.2.19"
    namespace: kube-system
    valuesFile: multus-cni/values.yml
    priority: -107
  metrics-server:
    <<: *default
    chart: metrics-server/metrics-server
    version: "3.13.0"
    namespace: kube-system
    valuesFile: metrics-server/values.yml
    priority: -106
  cert-manager:
    <<: *default
    chart: jetstack/cert-manager
    version: "v1.18.2"
    namespace: cert-manager
    valuesFile: cert-manager/values.yml
    priority: -99
    hooks:
      postInstall: cert-manager/post-install.yml
  traefik:
    <<: *default
    chart: traefik/traefik
    version: "v36.3.0"
    namespace: traefik
    valuesFile: traefik/values.yml
    priority: -98
  keel:
    <<: *default
    chart: keel/keel
    version: "1.0.5"
    namespace: keel
    valuesFile: keel/values.yml
    priority: -97
  cloudflare-ddns:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: cloudflare-ddns
    valuesFile: cloudflare-ddns/values.yml
    priority: -96
  external-dns:
    <<: *default
    chart: external-dns/external-dns
    version: "1.18.0"
    namespace: external-dns
    valuesFile: external-dns/values.yml
    priority: -95
  authentik:
    <<: *default
    chart: authentik/authentik
    version: "2025.6.4"
    namespace: authentik
    valuesFile: authentik/values.yml
    priority: -88
  jdownloader:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: jdownloader
    valuesFile: jdownloader/values.yml
    priority: -78
  plex:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: plex
    valuesFile: plex/values.yml
    priority: -69
  mosquitto:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: mosquitto
    valuesFile: mosquitto/values.yml
    priority: -59
  zigbee2mqtt:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: home-assistant
    valuesFile: home-assistant/zigbee2mqtt.values.yml
    priority: -58
  node-red:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: home-assistant
    valuesFile: home-assistant/nodered.values.yml
    priority: -57
  esphome:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: home-assistant
    valuesFile: home-assistant/esphome.values.yml
    priority: -56
  home-assistant:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: home-assistant
    valuesFile: home-assistant/home-assistant.values.yml
    priority: -55
  changedetection:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: changedetection
    valuesFile: changedetection/values.yml
    priority: -55
  mcp-weather:
    <<: *default
    chart: bjw-s/app-template
    version: "4.1.2"
    namespace: mcps
    valuesFile: mcps/mcp-weather.values.yml
    priority: -49
