metadata:
  org: github.com/igalarzab/homelab
  maintainer: Jose Galarza

settings:
  kubeContext: jupyter

namespaces:
  cert-manager:
  datastores:
  external-dns:
  github-actions:
  keel:
  kube-system:
  pocket-id:
  traefik:
    # Host ports require an exception; retain restricted policy warnings and auditing.
    labels:
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/warn: restricted
      pod-security.kubernetes.io/warn-version: latest
      pod-security.kubernetes.io/audit: restricted
      pod-security.kubernetes.io/audit-version: latest

helmRepos:
  hcloud: https://charts.hetzner.cloud
  bjw-s: https://bjw-s-labs.github.io/helm-charts
  containeroo: https://charts.containeroo.ch
  external-dns: https://kubernetes-sigs.github.io/external-dns/
  metrics-server: https://kubernetes-sigs.github.io/metrics-server/
  jetstack: https://charts.jetstack.io
  keel: https://charts.keel.sh
  traefik: https://traefik.github.io/charts

appsTemplates:
  default: &default
    enabled: true
    protected: false
    test: false
    wait: true

apps:
  local-path-provisioner:
    <<: *default
    chart: containeroo/local-path-provisioner
    version: "0.0.38"
    namespace: kube-system
    valuesFile: local-path-provisioner/values.yml
    hooks:
      postInstall: local-path-provisioner/post-install.yml
      postUpgrade: local-path-provisioner/post-install.yml
  csi-driver-hetzner:
    <<: *default
    chart: hcloud/hcloud-csi
    version: "2.23.0"
    namespace: kube-system
    valuesFile: csi-driver-hetzner/values.yml
  metrics-server:
    <<: *default
    chart: metrics-server/metrics-server
    version: "3.14.0"
    namespace: kube-system
    valuesFile: metrics-server/values.yml
  cert-manager:
    <<: *default
    chart: jetstack/cert-manager
    version: "v1.21.1"
    namespace: cert-manager
    valuesFile: cert-manager/values.yml
    hooks:
      postInstall: cert-manager/post-install.yml
      postUpgrade: cert-manager/post-install.yml
  external-dns:
    <<: *default
    chart: external-dns/external-dns
    version: "1.21.1"
    namespace: external-dns
    valuesFile: external-dns/values.yml
  traefik:
    <<: *default
    chart: traefik/traefik
    version: "41.5.0"
    namespace: traefik
    valuesFile: traefik/values.yml
  pocket-id:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: pocket-id
    valuesFile: pocket-id/values.yml
  github-actions:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: github-actions
    valuesFile: github-actions/values.yml
    priority: -59
  postgresql:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: datastores
    valuesFile: datastores/postgresql.yml
  redis:
    <<: *default
    chart: bjw-s/app-template
    version: "5.1.0"
    namespace: datastores
    valuesFile: datastores/redis.yml
