---

- hosts: servers
  gather_facts: yes
  vars_prompt:
    - name: cifs_multimedia_password
      prompt: Enter the SAMBA3 Multimedia volume password (omit to skip)
  roles:
    - role: base
    - role: kubeadm
