home_sexy_atmosphere:
  alias: Home Sexy Atmosphere
  icon: mdi:cards-heart
  mode: single
  sequence:
    - service: script.helper_music
      data:
        player_id: media_player.home_speakers
        player_name: Home Speakers
        playlist: spotify:playlist:3zcPcs4KmtQLQ0jnVV031J
    - service: cover.close_cover
      entity_id: group.home_curtains
