home_sleeping_mode:
  alias: Home Sleeping Mode
  icon: mdi:bed
  mode: single
  sequence:
    - service: timer.start
      entity_id: timer.bedroom_sleeping
    - service: media_player.turn_off
      entity_id: media_player.living_room_tv
    - service: media_player.turn_off
      entity_id: media_player.home_speakers
    - service: cover.close_cover
      entity_id: group.home_curtains
