home_sexy_lights:
  alias: Home Sexy Lights
  icon: mdi:cards-heart
  mode: single
  sequence:
    - service: light.turn_off
      entity_id: light.kitchen_lights
    - service: light.turn_off
      entity_id: light.hall_lights
    - service: light.turn_on
      entity_id: light.living_room_lights_tv
    - service: light.turn_on
      entity_id: light.living_room_lights_ceiling
      data:
        brightness_pct: 20
        transition: 5
        rgb_color:
          - 255
          - 72
          - 163
    - service: light.turn_on
      entity_id: light.living_room_lights_sofa
      data:
        brightness_pct: 20
        transition: 5
        rgb_color:
          - 255
          - 72
          - 118
    - service: light.turn_on
      entity_id: light.bedroom_lights
      data:
        brightness_pct: 20
        transition: 5
        rgb_color:
          - 255
          - 72
          - 163
