home_wakeup:
  alias: Home Wake Up
  icon: mdi:bed-empty
  mode: single
  sequence:
    - service: timer.finish
      entity_id: timer.bedroom_sleeping
    - service: script.helper_music
      data:
        volume_level: 0.05
        player_id: media_player.home_speakers
        player_name: Home Speakers
        playlist: spotify:playlist:37i9dQZF1EIdJI2xV2PSSs
    - service: cover.open_cover
      entity_id: group.home_curtains
