living_room_chill_lights:
  alias: Living Room Chill Lights
  icon: mdi:sofa
  mode: single
  fields:
    brightness_pct:
      description: Brightness percentage (value from 0 to 100)
      selector:
        number:
          min: 0
          max: 100
  sequence:
    - service: light.turn_on
      entity_id: light.living_room_lights_ceiling
      data:
        brightness_pct: '{% if now().hour < 8 %}5{% else %}{{ brightness_pct|default(80) }}{% endif %}'
        rgb_color:
          - 255
          - 200
          - 145
    - service: light.turn_on
      entity_id: light.living_room_lights_sofa
      data:
        brightness_pct: '{% if now().hour < 8 %}5{% else %}{{ brightness_pct|default(80) }}{% endif %}'
        rgb_color:
          - 255
          - 145
          - 200
