living_room_chill_atmosphere:
  alias: Living Room Chill Atmosphere
  icon: mdi:sofa
  mode: single
  sequence:
    - service: script.helper_music
      data:
        player_id: media_player.living_room_speaker
        player_name: Living Room speaker
        playlist: spotify:playlist:37i9dQZF1DX889U0CL85jj
