---

apiVersion: v1
kind: Service
metadata:
  name: esphome
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: esphome
spec:
  selector:
    app.kubernetes.io/name: esphome
  ports:
    - name: http
      protocol: TCP
      port: 6052
      targetPort: http
