apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "plex.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plex.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          securityContext:
            privileged: true # TODO: Needed for quicksync
          env:
            - name: ADVERTISE_IP
              value: https://{{ .Values.plex.advertiseIp }}
            - name: PLEX_CLAIM
              value: {{ .Values.plex.claim | quote }}
            - name: TZ
              value: {{ .Values.plex.tz }}
            - name: PLEX_UID
              value: "1000"
            - name: PLEX_GID
              value: "100"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /identity
              port: http
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /identity
              port: http
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            - name: transcode
              mountPath: /transcode
            - name: quicksync
              mountPath: /dev/dri
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        - name: transcode
          emptyDir: {}
        - name: quicksync
          hostPath:
            path: /dev/dri
            type: Directory
        {{- toYaml . | nindent 8 }}
      {{- end }}
