---

- name: Copy config files for kubeadm and kubelet
  become: true
  template:
    src: "{{ item }}.j2"
    dest: "/etc/kubernetes/{{ item }}"
  with_list:
    - kubeadm-config.yml
    - kubelet.yml
  notify:
    - restart kubelet

- name: Check if the cluster has been already initialised
  become: true
  register: kubelet_cfg
  stat:
    path: /etc/kubernetes/admin.conf

- name: Initialize k8s control plane
  become: true
  register: kubeadm_init
  when: not kubelet_cfg.stat.exists
  command: kubeadm init --config /etc/kubernetes/kubeadm-config.yml

- name: Control plane output
  when: not kubelet_cfg.stat.exists
  debug:
    var: kubeadm_init.stdout
    verbosity: 2

