---

- name: Load network kernel modules
  become: true
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  with_list:
    - overlay
    - br_netfilter

- name: Configure sysctl for k8s
  become: true
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true
  with_items:
    - { name: 'net.ipv4.ip_forward', value: '1' }
    - { name: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }

