- platform: template
  sensors:
    unavailable_entities:
      friendly_name: Unavailable Entities
      value_template: >
        {{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) | list | length }}
      attribute_templates:
        entities: >
          {{ states | selectattr('state', 'in', ['unavailable', 'unknown', 'none']) |
                map(attribute='entity_id') | list | join(', ') }}
