apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jdownloader.fullname" . }}
  labels:
    {{- include "jdownloader.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "jdownloader.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jdownloader.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: TZ
              value: {{ .Values.jdownloader.tz }}
            - name: KEEP_APP_RUNNING
              value: "1"
            - name: USER_ID
              value: "1000"
            - name: GROUP_ID
              value: "100"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http 
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
