version: 4
availability:
  enabled: true
devices: devices.yaml
device_options: {}
groups: groups.yaml
advanced:
  channel: 25
  last_seen: ISO_8601
  log_level: info
  log_output:
    - console
  network_key: '!secrets.yaml network_key'
  pan_id: 3776
  timestamp_format: YYYY-MM-DDTHH:mm:ssZ
  transmit_power: 20
frontend:
  enabled: true
  port: 8080
homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: '!secrets.yaml server'
  user: '!secrets.yaml user'
  password: '!secrets.yaml password'
serial:
  port: tcp://10.31.7.40:6638
  baudrate: 115200
  adapter: zstack
  disable_led: false
