availability: true
groups: groups.yaml
devices: devices.yaml
device_options:
  legacy: false
advanced:
  channel: 25
  homeassistant_legacy_entity_attributes: false
  last_seen: ISO_8601
  legacy_api: false
  legacy_availability_payload: false
  log_level: info
  log_output: ['console']
  network_key: '!secrets.yaml network_key'
  pan_id: 3776
  timestamp_format: YYYY-MM-DDTHH:mm:ssZ
  transmit_power: 20
frontend:
  port: 8080
homeassistant:
  legacy_entity_attributes: false
  legacy_triggers: false
mqtt:
  base_topic: zigbee2mqtt
  server: '!secrets.yaml server'
  user: '!secrets.yaml user'
  password: '!secrets.yaml password'
serial:
  adapter: ember
  rtscts: false
  port: tcp://10.31.2.11:6638
  baudrate: 115200
  disable_led: false
