'0x00158d0001e0a23e':
  friendly_name: entrance/door
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Entrance Door
    device:
      suggested_area: Entrance
'0x00158d00066933ab':
  friendly_name: 'entrance/motion'
  optimistic: true
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Entrance Motion
    device:
      suggested_area: Entrance
'0x00158d000669412a':
  friendly_name: 'kitchen/motion'
  optimistic: true
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Kitchen Motion
    device:
      suggested_area: Kitchen
'0x00158d000484ff28':
  friendly_name: living_room/thermometer
  optimistic: true
  filtered_attributes: ['linkquality', 'power_outage_count', 'pressure', 'voltage']
  homeassistant:
    name: Living Room Thermometer
    device:
      suggested_area: Living Room
'0x00158d00028d8ebf':
  friendly_name: living_room/door_terrace_right
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Living Room Terrace Right Door
    device:
      suggested_area: Living Room
'0x00158d0006330376':
  friendly_name: living_room/door_terrace_left
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Living Room Terrace Left Door
    device:
      suggested_area: Living Room
'0x8c65a3fffeb3ee1c':
  friendly_name: living_room/ir_controller
  optimistic: true
  filtered_attributes: ['linkquality']
  homeassistant:
    name: Living Room IR Controller
    device:
      suggested_area: Living Room
'0x00158d000669577b':
  friendly_name: hall/motion
  optimistic: true
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Hall Motion
    device:
      suggested_area: Hall
'0x00158d0006bec2e2':
  friendly_name: office/thermometer
  optimistic: true
  filtered_attributes: ['linkquality', 'power_outage_count', 'pressure', 'voltage']
  homeassistant:
    name: Office Thermometer
    device:
      suggested_area: Office
'0x00158d00067965b8':
  friendly_name: office/door
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Door
    device:
      suggested_area: Office
'0x00158d00028c583f':
  friendly_name: office/window_centre
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Centre Window
    device:
      suggested_area: Office
'0x00158d000633037a':
  friendly_name: office/window_right
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Right Window
    device:
      suggested_area: Office
'0xa49e69fffe90929b':
  friendly_name: office/motion
  optimistic: true
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Motion
    device:
      suggested_area: Office
'0x001788010b59c0e5':
  friendly_name: office/remote_desk
  optimistic: true
  filtered_attributes: ['linkquality', 'update', 'update_available']
  homeassistant:
    name: Office Remote Desk
    device:
      suggested_area: Office
'0x00158d00067be294':
  friendly_name: bathroom/door
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bathroom Door
    device:
      suggested_area: Bathroom
'0x00158d0006e45a7e':
  friendly_name: 'bathroom/motion'
  optimistic: true
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bathroom Motion
    device:
      suggested_area: Bathroom
'0x00158d000484feb0':
  friendly_name: bedroom/thermometer
  optimistic: true
  filtered_attributes: ['linkquality', 'power_outage_count', 'pressure', 'voltage']
  homeassistant:
    name: Bedroom Thermometer
'0x00158d0001e09fb1':
  friendly_name: bedroom/door
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Door
'0x0c4314fffe997804':
  friendly_name: bedroom/light_bed
  optimistic: true
  homeassistant:
    name: Bedroom Light Bed
    device:
      suggested_area: Bedroom
'0x00158d00028d6f3a':
  friendly_name: bedroom/window_right
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Right Window
    device:
      suggested_area: Bedroom
'0x00158d0005053085':
  friendly_name: bedroom/window_left
  optimistic: true
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Left Window
    device:
      suggested_area: Bedroom
'0x00158d0006695335':
  friendly_name: 'bedroom/motion'
  optimistic: true
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Motion
    device:
      suggested_area: Bedroom
