# Aqara Door/Window Sensors
'0x00158d0001e0a23e':
  friendly_name: entrance/door
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Entrance Door
    device:
      suggested_area: Entrance
    contact:
      device_class: door
      name: Contact
'0x00158d00028d8ebf':
  friendly_name: living_room/door_right
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Living Room Door Right
    device:
      suggested_area: Living Room
    contact:
      device_class: door
      name: Contact
'0x00158d0006330376':
  friendly_name: living_room/door_left
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Living Room Door Left
    device:
      suggested_area: Living Room
    contact:
      device_class: door
      name: Contact
'0x00158d00067965b8':
  friendly_name: office/door
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Door
    device:
      suggested_area: Office
    contact:
      device_class: door
      name: Contact
'0x00158d00028c583f':
  friendly_name: office/window_centre
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Window Centre
    device:
      suggested_area: Office
    contact:
      device_class: window
      name: Contact
'0x00158d000633037a':
  friendly_name: office/window_right
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Window Right
    device:
      suggested_area: Office
    contact:
      device_class: window
      name: Contact
'0x00158d00067be294':
  friendly_name: bathroom/door
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bathroom Door
    device:
      suggested_area: Bathroom
    contact:
      device_class: door
      name: Contact
'0x54ef441000caddb0':
  friendly_name: bathroom/door_shower
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bathroom Shower Door
    device:
      suggested_area: Bathroom
    contact:
      device_class: door
      name: Contact
'0x00158d0001e09fb1':
  friendly_name: bedroom/door
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Door
    device:
      suggested_area: Bedroom
    contact:
      device_class: door
      name: Contact
'0x00158d00028d6f3a':
  friendly_name: bedroom/window_right
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Window Right
    device:
      suggested_area: Bedroom
    contact:
      device_class: window
      name: Contact
'0x00158d0005053085':
  friendly_name: bedroom/window_left
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Window Left
    device:
      suggested_area: Bedroom
    contact:
      device_class: window
      name: Contact

# Aqara Motion Sensors
'0x00158d00066933ab':
  friendly_name: 'entrance/motion'
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Entrance Motion
    device:
      suggested_area: Entrance
'0x00158d000669412a':
  friendly_name: 'kitchen/motion'
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Kitchen Motion
    device:
      suggested_area: Kitchen
'0x00158d0006e45a7e':
  friendly_name: 'bathroom/motion'
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bathroom Motion
    device:
      suggested_area: Bathroom
'0x00158d0006695335':
  friendly_name: 'bedroom/motion'
  occupancy_timeout: 15
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Motion
    device:
      suggested_area: Bedroom

# Linptech Presence Sensor
'0xa49e69fffe90929b':
  friendly_name: office/motion
  debounce: 1
  filtered_attributes: ['battery_low', 'device_temperature', 'fading_time', 'linkquality', 'motion_detection_distance', 'motion_detection_sensitivity', 'power_outage_count', 'presence_keep_time', 'static_detection_sensitivity', 'tamper', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Motion
    device:
      suggested_area: Office

# Aqara Thermometers
'0x00158d000484ff28':
  friendly_name: living_room/thermometer
  filtered_attributes: ['linkquality', 'power_outage_count', 'pressure', 'voltage']
  homeassistant:
    name: Living Room Thermometer
    device:
      suggested_area: Living Room
'0x00158d0006bec2e2':
  friendly_name: office/thermometer
  filtered_attributes: ['linkquality', 'power_outage_count', 'pressure', 'voltage']
  homeassistant:
    name: Office Thermometer
    device:
      suggested_area: Office
'0x00158d000ae464b9':
  friendly_name: bathroom/thermometer
  filtered_attributes: ['linkquality', 'power_outage_count', 'pressure', 'voltage']
  homeassistant:
    name: Bathroom Thermometer
    device:
      suggested_area: Bathroom
'0x00158d000484feb0':
  friendly_name: bedroom/thermometer
  filtered_attributes: ['linkquality', 'power_outage_count', 'pressure', 'voltage']
  homeassistant:
    name: Bedroom Thermometer
    device:
      suggested_area: Bedroom
'0xa4c13811dcd50973':
  friendly_name: terrace/plant_thermometer
  filtered_attributes: ['battery_state', 'linkquality', 'temperature_unit']
  homeassistant:
    name: Terrace Plant Thermometer
    device:
      suggested_area: Terrace

# IR Blasters
'0x8c65a3fffeb3ee1c':
  friendly_name: living_room/ir_controller
  filtered_attributes: ['linkquality']
  homeassistant:
    name: Living Room IR Controller
    device:
      suggested_area: Living Room

# Phillips Hue Switches
'0x001788010b59c0e5':
  friendly_name: office/controller_desk
  filtered_attributes: ['linkquality']
  homeassistant:
    name: Office Controller Desk
    device:
      suggested_area: Office
'0x00178801096aa3ed':
  friendly_name: bedroom/controller_bed
  filtered_attributes: ['linkquality']
  homeassistant:
    name: Bedroom Controller Bed
    device:
      suggested_area: Bedroom
'0x001788010968e553':
  friendly_name: living_room/controller_sofa
  filtered_attributes: ['linkquality']
  homeassistant:
    name: Living Room Controller Sofa
    device:
      suggested_area: Living Room

# Aqara Switches E1
'0x54ef441000d68d4d':
  friendly_name: bathroom/controller_wall
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'power_outage_memory']
  homeassistant:
    name: Bathroom Controller Wall
    device:
      suggested_area: Bathroom
    switch_left:
      name: Switch Left
    switch_right:
      name: Switch Right
'0x54ef441000d68ffc':
  friendly_name: entrance/controller_wall
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'power_outage_memory']
  homeassistant:
    name: Entrance Controller Wall
    device:
      suggested_area: Entrance
    switch_left:
      name: Switch Left
    switch_right:
      name: Switch Right
'0x54ef441000d68889':
  friendly_name: kitchen/controller_wall
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'power_outage_memory']
  homeassistant:
    name: Kitchen Controller Wall
    device:
      suggested_area: Kitchen
    switch_left:
      name: Switch Left
    switch_right:
      name: Switch Right

# Aqara Switch Z1 Pro
'0x54ef441000bc376b':
  friendly_name: 'bedroom/controller_wall'
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Bedroom Controller Wall
    device:
      suggested_area: Bedroom
    switch_top:
      object_id: switch_one
    switch_center:
      object_id: switch_two
    switch_bottom:
      object_id: switch_three
    switch_one:
      name: Switch One
    switch_two:
      name: Switch Two
    switch_three:
      name: Switch Three
'0x54ef441000bc590f':
  friendly_name: living_room/controller_wall
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Living Room Controller Wall
    device:
      suggested_area: Living Room
    switch_top:
      object_id: switch_one
    switch_center:
      object_id: switch_two
    switch_bottom:
      object_id: switch_three
    switch_one:
      name: Switch One
    switch_two:
      name: Switch Two
    switch_three:
      name: Switch Three
'0x54ef441000bed284':
  friendly_name: office/controller_wall
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'trigger_count', 'voltage']
  homeassistant:
    name: Office Controller Wall
    device:
      suggested_area: Office
    switch_top:
      object_id: switch_one
    switch_center:
      object_id: switch_two
    switch_bottom:
      object_id: switch_three
    switch_one:
      name: Switch One
    switch_two:
      name: Switch Two
    switch_three:
      name: Switch Three

# Ikea Lights
'0x287681fffef1e8cc':
  friendly_name: bedroom/light_bed
  transition: ''
  color_sync: true
  state_action: false
  filtered_attributes: ['color_mode', 'color_options', 'color_temp_startup', 'linkquality']
  homeassistant:
    name: Bedroom Light Bed
    device:
      suggested_area: Bedroom

# Others
'0x00158d0005430faf':
  friendly_name: 'kitchen/vibration_countersink'
  filtered_attributes: ['device_temperature', 'linkquality', 'power_outage_count', 'voltage']
  homeassistant:
    name: Kintchen Countersink Vibration
    device:
      suggested_area: Kitchen
